# Generated by Django 4.1 on 2022-08-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя покупателя', max_length=100, verbose_name='Покупатель')),
                ('content', models.TextField(blank=True, help_text='Введите содержание заказа', null=True, verbose_name='Содержание заказа')),
                ('cost', models.FloatField(help_text='Введите общую стоимость', verbose_name='Общая стоимость')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
