# Generated by Django 4.1 on 2022-08-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_order_date_order_date_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование товара с ценой', max_length=100, verbose_name='Товар')),
                ('price', models.FloatField(help_text='Введите стоимость', verbose_name='Цена')),
            ],
        ),
    ]
